### ISSUE TITLE
RuntimeError: expected scalar type Double but found Float

### ISSUE THREAD

**Issue by inoryw** [Xillv/Code-for-AEGCN-Glove#3]
could you tell me how to solve this problem? thanks!
---
Traceback (most recent call last):
  File "train_AEGCN.py", line 231, in <module>
    ins.run()
  File "train_AEGCN.py", line 157, in run
    max_test_acc, max_test_f1 = self._train(criterion, optimizer)
  File "train_AEGCN.py", line 82, in _train
    outputs = self.model(inputs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\study\GCN\Code-for-AEGCN-Glove-master\models\aegcn.py", line 120, in forward
    x = F.relu(self.gc1(self.position_weight(text_out, aspect_double_idx, text_len, aspect_len), adj))
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\study\GCN\Code-for-AEGCN-Glove-master\models\aegcn.py", line 30, in forward
    hidden = torch.matmul(text, self.weight)
RuntimeError: expected scalar type Double but found Float

**Comment by Xillv** [comment]
in the code "hidden = torch.matmul(text,self.weight),the data type of text and self.weight must be the same
